# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2ad408608d3c4b46020e163f0504fdfceba088027254fe45b6327e56017415484dfd4b4bd20e481d3308abfd74fab47fc1df2d206b0cd82048ec1f5502f016

test:
  secret_key_base: de68f03c0501fc86ff3a31926814b87cc99f2723b3107f8d728a421080306610c4cb56694de89ca93138eb07243599505ecf9eea83e00932353a2780574b40c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
